name: "calibrate_train_larger"
defaults:
  - all@_global_: default_calibrate
  - _self_

apply_on: ["val","test"]
save_outputs: true

calib:
  on_split: "train"
  list_types: ["quantile_spline"]
  box_bins: [2, 3, 4, 5, 6] #
  conf_bins: [14,16,18,20, 24, 28, 34, 40, 50] #

optim:
  metrics: ["tradeoff_full", "oracle"]
  k_folds: 20
  oracle_on: "val"

